### ISSUE TITLE
View All Artworks

### ISSUE THREAD

**Issue by Bonni535** [nss-evening-cohort-24/24-26-hack-visual-virtuoso-BE#4]
# Read Artworks
this is for the implementation of a request that grabs the all the artworks entities for displaying.

# Request
- Method: GET
- Path: /artworks

# Response
- Body 
```c#
{
  "id": int,
  "title": string,
  "imageUrl": url,
  "userId": int
}
```

# Acceptance Criteria
- Status Code: 200 OK
- The response body contains all posts
- Each post has the response body listed

# Example Code
```c#

app.MapGet("/artists", (TunaPianoDbContext db) => //getAllArtists
{
    return db.Artists.ToList();
});
```

**Comment by ndswimming92** [comment]
```csharp
// Get All Artwork
app.MapGet("/api/artwork", (HackVisualVirtuosoBEDbContext db) =>
{
    return db.Artwork.ToList();
});
```
